// export { Cart, Header, Profile, Login, Register };
export { default as Login } from "./Login"
export { default as Cart } from "./Cart"
export { default as Header } from "./Header"
export { default as Register } from "./Register"
export { default as Profile } from "./Profile"
export { default as Home } from "./Home"
export { default as Jumbotron } from "./Jumbotron"
export { default as Footer } from "./Footer"
export { default as DetailItem } from "./DetailItem"
